### ISSUE TITLE
Add OARS and Version tags to appdata

### ISSUE THREAD

**Issue by nedrichards** [flathub/ch.x29a.playitslowly#1]
Flathub has expanded its appdata requirements and applications now need OARS and Version tags.

e.g. https://hughsie.github.io/oars/

Lack of these tags may affect visibility in software centers or the website.

**Comment by bochecha** [comment]
I'll happily take a pull request, otherwise it might be a while before I get to this.

**Comment by nedrichards** [comment]
Yeah, fair enough. I'll have a look myself if I get time (and obviously do it upstream). This was more of a reminder bug for me since at some point we'll be actively enforcing metadata in new builds.

**Comment by bochecha** [comment]
I guess neither of us got the time in all of 2019. :rofl: 

I'm working on this in #2 now.
